import { Team, Driver } from "../shared/types";

export const teams: Team[] = [
  {
    id: 1,
    name: "Red Bull Racing",
    base: "Milton Keynes, United Kingdom",
    teamPrincipal: "Christian Horner",
    worldChampionships: 6,
    founded: 2005,
  },
  {
    id: 2,
    name: "Mercedes-AMG Petronas Formula One Team",
    base: "Brackley, United Kingdom",
    teamPrincipal: "Toto Wolff",
    worldChampionships: 8,
    founded: 2010,
  },
  {
    id: 3,
    name: "Scuderia Ferrari",
    base: "Maranello, Italy",
    teamPrincipal: "Fred Vasseur",
    worldChampionships: 16,
    founded: 1950,
  },
  {
    id: 4,
    name: "McLaren Racing",
    base: "Woking, United Kingdom",
    teamPrincipal: "Zak Brown",
    worldChampionships: 8,
    founded: 1966,
  },
  {
    id: 5,
    name: "Aston Martin Aramco Cognizant Formula One Team",
    base: "Silverstone, United Kingdom",
    teamPrincipal: "Mike Krack",
    worldChampionships: 0,
    founded: 2021,
  },
  {
    id: 6,
    name: "Alpine F1 Team",
    base: "Enstone, United Kingdom",
    teamPrincipal: "Otmar Szafnauer",
    worldChampionships: 2,
    founded: 1981,
  },
];

export const drivers: Driver[] = [
  {
    id: 1,
    teamId: 1,
    name: "Max Verstappen",
    nationality: "Dutch",
    dateOfBirth: "1997-09-30",
    championshipsWon: 3,
    carNumber: 33,
  },
  {
    id: 2,
    teamId: 1,
    name: "Sergio Pérez",
    nationality: "Mexican",
    dateOfBirth: "1990-01-26",
    championshipsWon: 0,
    carNumber: 11,
  },
  {
    id: 3,
    teamId: 2,
    name: "Lewis Hamilton",
    nationality: "British",
    dateOfBirth: "1985-01-07",
    championshipsWon: 7,
    carNumber: 44,
  },
  {
    id: 4,
    teamId: 2,
    name: "George Russell",
    nationality: "British",
    dateOfBirth: "1998-02-15",
    championshipsWon: 0,
    carNumber: 63,
  },
  {
    id: 5,
    teamId: 3,
    name: "Charles Leclerc",
    nationality: "Monégasque",
    dateOfBirth: "1997-10-16",
    championshipsWon: 0,
    carNumber: 16,
  },
  {
    id: 6,
    teamId: 3,
    name: "Carlos Sainz",
    nationality: "Spanish",
    dateOfBirth: "1994-09-01",
    championshipsWon: 0,
    carNumber: 55,
  },
  {
    id: 7,
    teamId: 4,
    name: "Lando Norris",
    nationality: "British",
    dateOfBirth: "1999-11-13",
    championshipsWon: 0,
    carNumber: 4,
  },
  {
    id: 8,
    teamId: 4,
    name: "Oscar Piastri",
    nationality: "Australian",
    dateOfBirth: "2001-04-06",
    championshipsWon: 0,
    carNumber: 81,
  },
  {
    id: 9,
    teamId: 5,
    name: "Fernando Alonso",
    nationality: "Spanish",
    dateOfBirth: "1981-07-29",
    championshipsWon: 2,
    carNumber: 14,
  },
  {
    id: 10,
    teamId: 5,
    name: "Lance Stroll",
    nationality: "Canadian",
    dateOfBirth: "1998-10-29",
    championshipsWon: 0,
    carNumber: 18,
  },
  {
    id: 11,
    teamId: 6,
    name: "Pierre Gasly",
    nationality: "French",
    dateOfBirth: "1996-02-07",
    championshipsWon: 0,
    carNumber: 10,
  },
  {
    id: 12,
    teamId: 6,
    name: "Esteban Ocon",
    nationality: "French",
    dateOfBirth: "1996-09-17",
    championshipsWon: 0,
    carNumber: 31,
  },
];
